#!/usr/bin/env bash
# Generate local OPAL dev secrets for secure-mode compose (ADR 0011).
# Writes deploy/opal/dev-secrets.env and deploy/opal/keys/ (both gitignored).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
KEY_DIR="$ROOT/deploy/opal/keys"
SECRETS="$ROOT/deploy/opal/dev-secrets.env"

mkdir -p "$KEY_DIR"

if [[ ! -f "$KEY_DIR/opal_rsa" ]]; then
  ssh-keygen -t rsa -b 4096 -m PEM -f "$KEY_DIR/opal_rsa" -N "" -q
fi

private_oneline() {
  awk 'NR>1{printf "_"} {gsub(/\r/,""); printf "%s", $0}' "$KEY_DIR/opal_rsa"
}

public_oneline() {
  tr -d '\n' < "$KEY_DIR/opal_rsa.pub"
}

gen_secret() {
  openssl rand -base64 32 | tr -d '/+=' | head -c 43
}

MASTER="$(gen_secret)"
WEBHOOK="$(gen_secret)"
ADMIN="$(gen_secret)"

cat > "$SECRETS" <<EOF
# Generated by generate-opal-dev-secrets.sh — do not commit
OPAL_AUTH_PRIVATE_KEY="$(private_oneline)"
OPAL_AUTH_PUBLIC_KEY="$(public_oneline)"
OPAL_AUTH_MASTER_TOKEN=${MASTER}
OPAL_POLICY_REPO_WEBHOOK_SECRET=${WEBHOOK}
OPAL_POLICY_REPO_POLLING_INTERVAL=300
CHEX_OPAL_SECURE=1
CHEX_ADMIN_SECRET=${ADMIN}
EOF

chmod 600 "$SECRETS" "$KEY_DIR/opal_rsa"
echo "Wrote $SECRETS (and keys under deploy/opal/keys/)"
